/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    fontFamily: {
      inter: ['Inter', 'sans-serif'],
    },
    extend: {
      colors: {
        surface: '#0e0e10',
        'surface-bright': '#2b2c32',
        'surface-container': '#19191d',
        'surface-container-high': '#1f1f24',
        'surface-container-highest': '#25252b',
        'surface-container-low': '#131316',
        'surface-container-lowest': '#000000',
        'surface-lowest': '#000000',
        'surface-dim': '#0e0e10',
        'surface-variant': '#25252b',
        'on-surface': '#e7e4ec',
        'on-surface-variant': '#acaab1',
        primary: '#adc6ff',
        'primary-container': '#004395',
        'primary-dim': '#98b8ff',
        'on-primary': '#003d88',
        'on-primary-container': '#bdd0ff',
        secondary: '#9d9da4',
        'secondary-container': '#3a3b41',
        'on-secondary': '#1e2025',
        'on-secondary-container': '#bebfc5',
        tertiary: '#e1dcfd',
        'tertiary-container': '#d3ceef',
        'on-tertiary': '#504d68',
        'on-tertiary-container': '#47445f',
        error: '#ee7d77',
        'error-container': '#7f2927',
        'on-error': '#490106',
        'on-error-container': '#ff9993',
        outline: '#75757c',
        'outline-variant': '#47474e',
      },
    },
  },
  plugins: [],
}
